spring:
  application:
    name: quietseoul

  datasource:
    url: jdbc:mysql://quietseoul-db.cp8swmeae41k.ap-northeast-2.rds.amazonaws.com:3306/quietseoul_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: hanjeok321!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration: 7200000
